import type { Proposal } from "./types";

export const OPERATOR_ADDRESS = "0x0a11e5e0000000000000000000000000000e5e00";
export const BACKER_ADDRESS = "0xb4ce00000000000000000000000000000000b4ce";
export const CREATOR_A = "0x4b8e21c0a7f1d9e4a6c3b8d0e2f4a6c8d0e2f4a6";
export const CREATOR_B = "0x91d3a0b7c4e8f2a6d0c4b8e2f6a0d4c8b2e6a0d4";

const T = (iso: string) => new Date(iso).getTime();

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: "prop-field-notes",
    title: "Field Notes, Vol. I",
    description:
      "A 64-page analog zine of night walks through old port cities. Printed on uncoated stock in an edition of 200, each copy bound by hand and paired with a numbered print.",
    cover: "/covers/field-notes.jpg",
    pricePerNft: 24,
    fundingGoal: 4800,
    type: "project",
    projectTwitter: "fieldnotesclub",
    creatorTwitter: "maker_a",
    projectInstagram: "field.notes",
    creatorInstagram: "maker.a",
    validTill: "2026-09-15",
    creator: CREATOR_A,
    createdAt: T("2026-08-19T10:00:00.000Z"),
    likes: 14,
    dislikes: 4,
    voters: {
      [BACKER_ADDRESS]: "like",
      [OPERATOR_ADDRESS]: "like",
      [CREATOR_B]: "like",
    },
    status: "passed",
    stablecoin: "SPRK",
    staked: false,
    totalFunding: 0,
    mintedCount: 0,
    backers: [],
    milestones: [],
    withdrawn: false,
  },
  {
    id: "prop-harbor",
    title: "Harbor Protocol",
    description:
      "An open mapping of neglected tidal infrastructure — a public dataset, a field kit for coastal stewards, and a season of documented surveys along two estuaries.",
    cover: "/covers/harbor.jpg",
    pricePerNft: 40,
    fundingGoal: 12000,
    type: "event",
    projectTwitter: "harborprotocol",
    creatorTwitter: "maker_a",
    validTill: "2026-09-03",
    creator: CREATOR_A,
    createdAt: T("2026-08-07T10:00:00.000Z"),
    likes: 31,
    dislikes: 5,
    voters: { [BACKER_ADDRESS]: "like" },
    status: "crowdfunding",
    stablecoin: "SPRK",
    startDate: "2026-08-24",
    endDate: "2026-09-21",
    staked: true,
    totalFunding: 5200,
    mintedCount: 130,
    backers: [{ address: BACKER_ADDRESS, minted: 4, amount: 160 }],
    milestones: [],
    withdrawn: false,
  },
  {
    id: "prop-atelier",
    title: "North Light Residency",
    description:
      "A three-month studio residency for two makers. NFT holders share scheduled studio access and receive a print from the term. Yield from later editions is split with holders.",
    cover: "/covers/atelier.jpg",
    pricePerNft: 80,
    fundingGoal: 8000,
    type: "creative-work",
    projectTwitter: "northlightres",
    creatorTwitter: "maker_b",
    validTill: "2026-08-26",
    creator: CREATOR_B,
    createdAt: T("2026-07-19T10:00:00.000Z"),
    likes: 22,
    dislikes: 3,
    voters: { [BACKER_ADDRESS]: "like" },
    status: "active",
    stablecoin: "SPRK",
    startDate: "2026-07-29",
    endDate: "2026-08-26",
    staked: true,
    totalFunding: 8160,
    mintedCount: 102,
    backers: [{ address: BACKER_ADDRESS, minted: 2, amount: 160 }],
    milestones: [
      {
        id: "ms-atelier-1",
        title: "Studio fitted & first fellows seated",
        description:
          "North wall glazed, benches installed, and both residents moved in for week one.",
        proof: "https://sprk.club/proof/atelier-week-1",
        submittedAt: T("2026-08-25T10:00:00.000Z"),
        status: "submitted",
      },
    ],
    withdrawn: false,
  },
  {
    id: "prop-tape",
    title: "Tape Archive",
    description:
      "Digitizing a private collection of 1970s community radio — transfers, cataloguing, and a public listening room. Early supporters receive a lathe-cut disc of selected sessions.",
    cover: "/covers/tape.jpg",
    pricePerNft: 16,
    fundingGoal: 3200,
    type: "project",
    validTill: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    creator: CREATOR_B,
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    likes: 5,
    dislikes: 4,
    voters: { [BACKER_ADDRESS]: "like" },
    status: "voting",
    stablecoin: "SPRK",
    staked: false,
    totalFunding: 0,
    mintedCount: 0,
    backers: [],
    milestones: [],
    withdrawn: false,
  },
];
